### ISSUE TITLE
creating Sample to create a  Heightmap Collision with Normals

### ISSUE THREAD

**Issue by PedroAlvesq** [sharpdx/SharpDX-Samples#10]
The  sample demonstrates how to move objects along a heightmap. It is based on the Generated Geometry sample, which creates a landscape from a bitmap.
this is link in xna 4.0
http://xbox.create.msdn.com/en-US/education/catalog/sample/collision_3d_heightmap_normals
i try to port the example with no sucess

**Comment by Spirit30** [comment]
Looks like nothing could make it faster ((
