### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by nycos62** [sharpdx/SharpDX-Samples#46]
Hello, It's not an issue, it's a question

maybe I don't understand something, but all samples with Direct3D11 or Direct3D12 are not working on windows 7
(with message like : Unable to load DLL 'd3d12.dll' or Unable to load DLL 'd3dcompiler_47.dll')
I've installed Windows 10 SDK under Windows 7, and dll are still not compatible

Do a direct3D11 or 12 program never run under windows < 8 ?
Must I use only Direct3D9 to be sure to not encounter compatibility issues on multiple windows OS kind ?

**Comment by xoofx** [comment]
d3d12 is Windows 10 only.
d3d11 samples should work (at least minitri for example)
