### ISSUE TITLE
I cannot using SharpDX.XInput in any version of SharpDX

### ISSUE THREAD

**Issue by Misaka-0x447f** [sharpdx/SharpDX-Samples#52]
https://github.com/sharpdx/SharpDX-Samples/blob/master/Desktop/XInput/XGamepadApp/Program.cs
here is the example but i cannot using SharpDX.XInput in any cases. Failed to recognize the reason.
only these available here:
![image](https://user-images.githubusercontent.com/15797507/32407074-5439b03a-c1be-11e7-8ceb-2ba28a931cbc.png)

**Comment by jebwatson** [comment]
Need to go into Manage Nuget packages for the project and install the XInput package. This will add the class library for XInput. Same story for any of the other assemblies. They don't ship with the base SharpDx for whatever reason.
